### PR TITLE
Bug fix to uniqueBy to avoid passing nil values to given selector

### PR DESCRIPTION
**Pull request by svermeulen**

### CODE REVIEW

**Comment by Henkoglobin** [comment]
Hey, thanks for your contribution! I'll try to get to this today :)

**Review by Henkoglobin — APPROVED** [review]

**Comment by Henkoglobin** [comment]
Thanks again for your bugfix! I've merged it right now and added some unit tests for `uniqueBy` while I was at it. This makes you the first contributor to lazylualinq :D

**Comment by svermeulen** [comment]
Great!  I like your approach best compared to the other similar libraries (eg. luafun).  Thanks for sharing your work here.

**Comment by Henkoglobin** [comment]
Haha, you're welcome! If you'd like to share what you're using this for, I'd love to read about it in the [discussions](https://github.com/Henkoglobin/lazylualinq/discussions/1)

**Pull request merged**
